version: 0.2

env:
  shell: bash
  variables:
    ENV: "build"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
    commands:
      - sudo apt-get install -y build-essential texinfo libncurses6 libncurses-dev ncurses-doc libgmp10 libgmp-dev m4 libtool help2man pkg-config gettext automake autoconf libxml2 libxml2-dev libxml2-utils libcjson1 libcjson-dev
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:

artifacts:
  files:
    - '**/*'
  base-directory: src
